### ISSUE TITLE
The group with the "" ID doesn't exist. Verify the ID and try again.

### ISSUE THREAD

**Issue by loid345** [tuyennn/AutoInstagramPost#25]
![image](https://user-images.githubusercontent.com/20200970/58754014-17923580-84d1-11e9-831b-113b99eb63b5.png)

**Comment by volanar** [comment]
![image](https://user-images.githubusercontent.com/20200970/58754125-a2bffb00-84d2-11e9-84b3-3e09ef8ab3d0.png)

**Comment by loid345** [comment]
![image](https://user-images.githubusercontent.com/20200970/58754134-bd926f80-84d2-11e9-89f9-0f679151b67d.png)
