### ISSUE TITLE
Error on saved product.

### ISSUE THREAD

**Issue by michelsilvestre** [tuyennn/AutoInstagramPost#3]
Hi, I installed and configured your module via composer without any problem, I installed the dependency according to its orientation. I made the configuration of the module by adding user and password of instagram.  Only the custom hashteg configuration is disabled and the other options are enabled. 

When saving the product, no publication is generated in instagram and it does not return any error messages.

I used ubuntu + nginx + php7.1

Please, can you help me?

**Comment by tuyennn** [comment]
@michelsilvestre This was fix on latest commit from master commit #4

**Comment by michelsilvestre** [comment]
Thank you for helping me quickly. I made the update according to your orientation and after saving the product the publication does not arrive in Instagram. I did the test by setting the wrong password in the configuration and it shows no error.

**Comment by michelsilvestre** [comment]
OK. bug fixed ... after upgrade deletes the file created in the root * .dat folder and it worked .. the module generated 03 .dat files before it was just one.
