### ISSUE TITLE
Error : Please check product's images again 

### ISSUE THREAD

**Issue by dineshmanne** [tuyennn/AutoInstagramPost#33]
I am using Magento ver. 2.2.4 , Ubuntu 18.04 , 

1. Installed extension by downloading from github. Given my instagram username and password.
2. When i click on test connection it is giving message as "Connection Success"
3. Enabled observer after saving product, Now go to any product in catalog and save the product then you are getting error as " Please check product's images again " 
4. I debugged and got response from instagram as follows

Array ( [message] => upload_id is None [status] => fail ) 
5. I given 777 folder permissions for var , pub folders as well . still issue come up.
6. My instagram account is new one and confirmed my mobile number and photo also uploaded.

### Expected result (*)
1. Photo needs to upload to instagram when we click on POST or saving an product from backend.

### Actual result (*)
1. Getting an error message as "Please check product's images again "

**Comment by tuyennn** [comment]
```
[2019-11-30 04:10:28] main.CRITICAL: RESPONSE: Something is wrong. Please check your input and try again.
```
Ref issue:
https://github.com/mgp25/Instagram-API/issues/2971
