### ISSUE TITLE
Extension don't send post to Instagram

### ISSUE THREAD

**Issue by a-mahmoudieh** [tuyennn/AutoInstagramPost#5]
Hello Ms Tuyen Nguyen;

I met with "AutoInstagramPost" for magento via AloThemes's support theme and successfully installed it but now can't conecting it to may instagram.
I want to post my products from my magento 2 site to my instagram account automatically via your extension but it not work. I install it successfully but seams the API of it is an old Instagram API if possible help me to launch it
I expect when a new product is submitted, the product post automatically to be send to the Instagram account, is it a true expectation?

Please guide me

Alireza Mahmoudieh

**Comment by tuyennn** [comment]
Hi @a-mahmoudieh. Thank you for your report.
To help us process this issue please make sure that you provided the following information:

* [ ]  Summary of the issue

* [ ]  Information on your environment

 * [ ]  Steps to reproduce

 * [ ]  Expected and actual results

**Comment by a-mahmoudieh** [comment]
1- This extention don't send new post to instagram for new product.
2- We have online market in persian language.
3- If need we reset configuration in our side please explain it if not please solve the problem of the 
    extension.
4- I want the extension send a new post to Instagram in same time that we submit the new product on 
    our Magento 2 site.

**Comment by tuyennn** [comment]
@a-mahmoudieh You'd need to upgrade the extension to latest version, this now support 2.2 and 2.3
